name: Generate tokenized calendar feeds

on:
  workflow_dispatch: {}
  schedule:
    # 06:00 Europe/Stockholm ≈ 04:00 UTC
    - cron: '0 4 * * *'

permissions:
  contents: write

env:
  FEEDS_DIR: _feeds/docs/feeds
  FEEDS_WORKDIR: _feeds
  EVENTS_DIR: _feeds/events
  TOKEN_MAP_PATH: _feeds/token_map.json
  UPSTREAM_STATE_PATH: _feeds/upstream_state.json
  PYTHONUNBUFFERED: '1'

jobs:
  build:
    runs-on: ubuntu-latest
    # Only run feed generation on main branch
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout public repo (site)
        uses: actions/checkout@v4

      - name: Checkout private feeds repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.FEEDS_REPO }}   # e.g. yourorg/private-feeds
          token: ${{ secrets.FEEDS_REPO_TOKEN }}  # classic PAT with repo access
          path: _feeds

      # Mask known secrets so they won’t appear if accidentally echoed
      - name: Mask secrets in logs
        run: |
          echo "::add-mask::${{ secrets.SOURCE_ICS_URL }}"
          echo "::add-mask::${{ secrets.BASE_URL }}"
          echo "::add-mask::${{ secrets.FEEDS_REPO_TOKEN }}"
          echo "::add-mask::${{ secrets.FEEDS_REPO }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install deps
        run: uv pip install --system -r requirements.txt

      - name: Ensure site folders
        run: |
          mkdir -p _feeds/docs/feeds
          touch _feeds/docs/.nojekyll

      - name: Generate feeds
        env:
          # upstream URL optional; if empty, script uses local fallback (personal.ics)
          SOURCE_ICS_URL: ${{ secrets.SOURCE_ICS_URL }}
          # where to read course rules + where to persist token/state
          EVENTS_DIR: ${{ env.EVENTS_DIR }}
          TOKEN_MAP_PATH: ${{ env.TOKEN_MAP_PATH }}
          UPSTREAM_STATE_PATH: ${{ env.UPSTREAM_STATE_PATH }}
          # where to write public ICS feeds
          FEEDS_DIR: ${{ env.FEEDS_DIR }}
          # quiet logging; set DEBUG for local runs only
          LOG_LEVEL: INFO
        run: python -m scripts.main

      # Commit and push to the private feeds repository
      - name: Commit & push updated feeds to private repo
        working-directory: _feeds
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/feeds/*.ics || true
          git add docs/.nojekyll || true
          git add token_map.json || true
          git add upstream_state.json || true
          git commit -m "Update tokenized feeds and state"
          git push
